### ISSUE TITLE
Code structure

### ISSUE THREAD

**Issue by asarkar** [PacktPublishing/Mastering-Akka#1]
Given that there are 10 chapters in the book, 109 SBT projects indicate poor code management. In order to read a chapter, I have to open 11 projects on an average in the IDE.
```
asarkar:Mastering-Akka$ find . -name "build.sbt" -type f | wc -l
     109
```
What may help is to have a single project for a chapter, named accordingly. The separate samples in a project can be submodules.

**Comment by domdorn** [comment]
I think a better approach would be to use one project and have the different stages as tags. That way, we could jump between the different steps and also see a diff of the changes. However, as the book is already published, I don't think this is going to happen.

**Comment by VishalMewadaPackt** [comment]
Hello Dominik,

Please let me know the code bundle structure which will help the reader more effectively. We'll make the necessary changes.

You can fork the code repo and make the changes, then you can push it so I can accept the pull request.

If you have any queries, please let me know.

Regards,

**Comment by asarkar** [comment]
Must be nice to be able to close tickets without having to do anything.
