### ISSUE TITLE
BookstorePlan does not compile 

### ISSUE THREAD

**Issue by gajaka** [PacktPublishing/Mastering-Akka#7]
Hi Mastering AKKA, 
In the BookstorePlan.scala I cannot find the reference of the util.
I am getting compile errors in **unapply** and **respond** method of the **IntPathElement** object. 
In other words: util.Try, case util.Success and util.Failure reports error such as "cannot resolve reference Success, Failure" e.t.c.
Can you please consider this issue .

**Comment by packt-pradeeps** [comment]
Please reopen the issue it it still persists.
